using Platform.Domain.Common;
using Platform.Domain.Enums;

namespace Platform.Domain.Entities;

public class Table : TenantEntity
{
    public string TableNumber { get; set; } = default!;
    public int Capacity { get; set; }
    public string? Location { get; set; }
    public string QrToken { get; set; } = Guid.NewGuid().ToString("N");
    public bool IsActive { get; set; } = true;

    public Restaurant? Restaurant { get; set; }
}

public class Order : TenantEntity
{
    /// <summary>Short random human-readable order code (e.g. "A3F9K"), unique per restaurant — generated
    /// in PublicOrdersController.GenerateOrderCode. Doesn't reveal order volume the way a sequential
    /// number would, and stays a fixed length regardless of how many orders the restaurant has taken.</summary>
    public string OrderNumber { get; set; } = default!;

    public OrderType OrderType { get; set; }
    public Guid? TableId { get; set; }
    public Table? Table { get; set; }

    public Guid? CustomerId { get; set; }
    public Customer? Customer { get; set; }
    public string? CustomerName { get; set; }
    public string? CustomerPhone { get; set; }
    public string? CustomerEmail { get; set; }

    public Guid? DeliveryAddressId { get; set; }
    public CustomerAddress? DeliveryAddress { get; set; }

    public decimal Subtotal { get; set; }
    public decimal DeliveryFee { get; set; }
    /// <summary>The delivery zone that priced this order ("Hafod"), or "Anywhere else" for an
    /// address inside no drawn zone. Snapshot - renaming a zone later doesn't change old orders.</summary>
    public string? DeliveryZoneName { get; set; }
    public decimal ProcessingFee { get; set; }
    public decimal DiscountAmount { get; set; }
    public Guid? VoucherId { get; set; }
    public string? VoucherCodeSnapshot { get; set; }
    public int LoyaltyPointsRedeemed { get; set; }
    public int LoyaltyPointsEarned { get; set; }
    public decimal TotalAmount { get; set; }

    public PaymentMethod PaymentMethod { get; set; }
    /// <summary>Name of a PaymentStatusDefinition row, not an enum - see StatusDefinitions.cs.</summary>
    public string PaymentStatus { get; set; } = default!;
    /// <summary>Name of an OrderStatusDefinition row, not an enum - see StatusDefinitions.cs.</summary>
    public string Status { get; set; } = default!;
    public DateTimeOffset? EstimatedReadyAt { get; set; }

    /// <summary>Planned minutes until ready/delivered, from the restaurant's default for the order
    /// type (staff can change it). The clock only starts when the order is confirmed - i.e. first
    /// moved off the starting status - which is when EstimatedReadyAt gets set.</summary>
    public int? EstimatedMinutes { get; set; }
    public string? SpecialRequests { get; set; }
    public OrderSource Source { get; set; } = OrderSource.Web;
    // IsDeleted/CreatedBy/UpdatedBy come from Entity - AppDbContext stamps CreatedBy/UpdatedBy
    // automatically from ICurrentActor, and IsDeleted is filtered out by the global query filter.

    // POS (dine-in) details - null on web orders.
    public int? GuestCount { get; set; }
    public Guid? WaiterUserId { get; set; }
    public DateTimeOffset? ClosedAt { get; set; }
    public string? DiscountReason { get; set; }
    public Guid? DiscountApprovedByUserId { get; set; }
    /// <summary>GUID generated by the POS hub; unique per restaurant, so a sync retry upserts
    /// instead of duplicating.</summary>
    public Guid? ClientId { get; set; }

    public List<OrderItem> Items { get; set; } = [];
    public List<OrderStatusHistory> StatusHistory { get; set; } = [];
    public List<Payment> Payments { get; set; } = [];
    public List<Refund> Refunds { get; set; } = [];
}

public class OrderItem : TenantEntity
{
    public Guid OrderId { get; set; }
    public Order? Order { get; set; }

    public Guid MenuItemId { get; set; }
    public string NameSnapshot { get; set; } = default!;
    public decimal UnitPriceSnapshot { get; set; }
    public int Quantity { get; set; } = 1;
    public string? SpecialInstructions { get; set; }
    public decimal LineTotal { get; set; }

    public OrderItemStatus ItemStatus { get; set; } = OrderItemStatus.Pending;
    public DateTimeOffset? SentAt { get; set; }
    public string? VoidReason { get; set; }

    public List<OrderItemModifier> Modifiers { get; set; } = [];
}

/// <summary>Full or partial refund. Never edits the order; reports subtract refunds.</summary>
public class Refund : TenantEntity
{
    public Guid OrderId { get; set; }
    public Order? Order { get; set; }

    /// <summary>Set when the POS created it (sync idempotency), like Order.ClientId.</summary>
    public Guid? ClientId { get; set; }
    public decimal Amount { get; set; }
    public RefundMethod Method { get; set; }
    public string? Reason { get; set; }
    /// <summary>Optional [{orderItemId, quantity}] for an item-level refund.</summary>
    public string? ItemsJson { get; set; }
    public Guid? RefundedByUserId { get; set; }
    public Guid? ApprovedByUserId { get; set; }
}

/// <summary>A receipt/kitchen/bar printer, configured on the POS hub and backed up here.</summary>
public class Printer : TenantEntity
{
    public string Name { get; set; } = default!;
    public PrinterRole Role { get; set; }
    public PrinterConnection Connection { get; set; }
    /// <summary>IP/host for Network, device or Windows printer name otherwise.</summary>
    public string? Address { get; set; }
    public int Port { get; set; } = 9100;
    public int Columns { get; set; } = 42;
    public Guid? HubDeviceId { get; set; }
    public bool IsActive { get; set; } = true;
}

public class OrderItemModifier : TenantEntity
{
    public Guid OrderItemId { get; set; }
    public OrderItem? OrderItem { get; set; }

    public Guid ModifierOptionId { get; set; }
    public string NameSnapshot { get; set; } = default!;
    public decimal PriceDeltaSnapshot { get; set; }
}

public class OrderStatusHistory : TenantEntity
{
    public Guid OrderId { get; set; }
    public Order? Order { get; set; }

    public string Status { get; set; } = default!;
    public Guid? ChangedByUserId { get; set; }
    public string? Note { get; set; }
    public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;
}

public class Payment : TenantEntity
{
    public Guid OrderId { get; set; }
    public Order? Order { get; set; }

    public PaymentProvider Provider { get; set; }
    public string? StripePaymentIntentId { get; set; }
    public decimal Amount { get; set; }
    public string Currency { get; set; } = "GBP";
    /// <summary>Name of a PaymentStatusDefinition row, not an enum - see StatusDefinitions.cs.</summary>
    public string Status { get; set; } = default!;
    public string? RawEventLogJson { get; set; }
}

/// <summary>Idempotency guard for Stripe webhook processing.</summary>
public class ProcessedPaymentEvent : Common.Entity
{
    public string Provider { get; set; } = "stripe";
    public string EventId { get; set; } = default!;
    public DateTimeOffset ProcessedAt { get; set; } = DateTimeOffset.UtcNow;
}
