// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Gln4vWmYbwlDgZ43tSsjSwAnOT4O0-o',
    appId: '1:628653334389:web:464cb86043c4ae5bfd7d3c',
    messagingSenderId: '628653334389',
    projectId: 'my-pos-81092',
    authDomain: 'my-pos-81092.firebaseapp.com',
    databaseURL: 'https://my-pos-81092-default-rtdb.firebaseio.com',
    storageBucket: 'my-pos-81092.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHg9qmyQhKFV-NkiAhCe8ilT7LY_8LaJ0',
    appId: '1:628653334389:android:d98b822ac419d10efd7d3c',
    messagingSenderId: '628653334389',
    projectId: 'my-pos-81092',
    databaseURL: 'https://my-pos-81092-default-rtdb.firebaseio.com',
    storageBucket: 'my-pos-81092.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Gln4vWmYbwlDgZ43tSsjSwAnOT4O0-o',
    appId: '1:628653334389:web:8e1d58047e8731cffd7d3c',
    messagingSenderId: '628653334389',
    projectId: 'my-pos-81092',
    authDomain: 'my-pos-81092.firebaseapp.com',
    databaseURL: 'https://my-pos-81092-default-rtdb.firebaseio.com',
    storageBucket: 'my-pos-81092.firebasestorage.app',
  );
}
